earc/admin_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

 
app_name = 'admin_app'

urlpatterns = [
    # =============Login and Logout===============
    path('login/', admin_login, name='admin_login'),
    path('logout/', admin_logout, name='admin_logout'),
    # =============Login and Logout===============

    # ==============Dashboard=====================
    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('get_chart_data/', get_chart_data, name='get_chart_data'),
    # =============Dashboard=======================

    # ==============Crud oprations=======================
    path('users/get_user', get_user, name="get_user"),
    path('users/delete/<int:id>/', user_crud_view.delete, name='delete_user'),
    path('users/', user_crud_view.load_table, name='load_table'),
    path('users/blocked/', user_crud_view.blocked_users, name='blocked_users'),
    path('user/create', user_crud_view.create_user, name='create_user'),
    path('user/<int:id>/update', user_crud_view.update_user, name='update_user'),
    path('user/<int:id>/block', user_crud_view.block_user, name='block_user'),
    path('user/<int:id>/unblock', user_crud_view.unblock_user, name='unblock_user'),
    path('sales_report/', sales_report, name='sales_report'),
    # ==============Crud oprations=======================

    #===============Settings===========================
    path('settings/', site_settings, name='site_settings'),
    path('logo/', logo, name='logo'),

    path('top_sellings/', top_sellings, name='top_sellings')
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/cart_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'cart_app'

urlpatterns = [
   path('', cart_management.view_cart, name='view_cart'),
   path('add/', cart_management.add_cart, name='add_item_to_cart'),
   path('remove/<int:id>/', cart_management.remove_item, name='remove_item'),
   path('update_quantity/', cart_management.update_quantity, name='update_quantity'),
   path('update_subtotal/', cart_management.update_subtotal, name='update_subtotal'),
   path('clear/', cart_management.clear_cart, name='clear_cart')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/earc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ============Direction django default admin panel=======
    path('django_admin/', admin.site.urls),

    # ========Direction to admin_app====================
    path('admin/', include('admin_app.urls', namespace='admin_app')),

    # ========Direction to admin_products_app==========
    path('admin/products/', include('admin_product_app.urls', namespace='admin_product_app')),

    # ===========Direction to banner_app===============
    path('admin/banner/', include('banner_app.urls', namespace='banner_app')),

    # ==============Direction to admin_order_app================
    path('admin/order/', include('admin_order_app.urls', namespace='admin_order_app')),

    # ===================Direction to admin_coupen_app=========================
    path('admin/coupen/', include('admin_coupen_app.urls', namespace='admin_coupen_app')),

    # ============Direction to offer_app========================
    path('admin/offers/', include('offer_app.urls', namespace='admin_offer_app')),

    #===========Direction to user_app=================
    path('', include('user_app.urls', namespace='user_app')),

    #===========Direction to user_product_app=========
    path('products/', include('user_product_app.urls', namespace='user_product_app')),

    # ============Direction to cart_management=======================
    path('cart/', include('cart_app.urls', namespace='cart_app')),


    # =============Direction to checkout_app======================
    path('checkout/', include('checkout_app.urls', namespace='checkout_app')),

    


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/offer_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'admin_offer_app'

urlpatterns = [
    # Category offers
    path('category/', list_category, name='list_category'),
    path('category/add/', add_category_offer, name='add_category_offer'),
    path('category/block_unblock/<int:id>/', block_unblock_category, name='block_unblock_category'),
    path('category/update/<int:id>/', update_category_offer, name='update_category_offer'),
    path('category/details/<int:id>/', category_offer_details, name='category_offer_details'),

    # Brand offers
    path('brand/', list_brand, name='list_brand'),
    path('brand/add/', add_brand_offer, name='add_brand_offer'),
    path('brand/block_unblock/<int:id>/', block_and_unblock_brand, name='block_and_unblock_brand'),
    path('brand/update/<int:id>/', update_brand_offer, name='update_brand_offer'),
    path('brand/details/<int:id>/', brand_details, name='brand_details')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/user_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

 
app_name = 'user_app'

urlpatterns = [
    path('', user_home, name='user_home'),
    path('register/', user_registration , name='user_registration'),
    path('otp/', otp_checking, name='otp_checking'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('resent_otp/', otp_resent, name='otp_resent'),
    path('404error/', fournoterror, name='fournoterror'),
    path('email/', forget_password_user_conform, name='forget_password_user_conform'),
    path('forget_otp/', sent_forget_password_otp, name='sent_forget_password_otp'),
    path('forget_password/', forget_password, name='forget_password'),
    path('change_password/', change_password, name='change_password'),
    path('account/', account_view, name='account_view'),
    path('user/', update_password, name='update_password'),
    path('details/<int:id>/', update_details, name='update_details'),
    path('address/', add_address, name='add_address'),
    path('address/<int:id>/', update_address, name='update_address'),
    path('delete_address/<int:id>/', delete_address, name='delete_address'),
    path('wallet/', wallet_view, name='wallet_view')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

earc/templates/admin_nav.html
{% load static %}

{% block content %}
<header class="main-header navbar">
    <div class="col-search">
        <form class="searchform">
            <div class="input-group">
                <input list="search_terms" type="text" class="form-control" placeholder="Search term">
                <button class="btn btn-light bg" type="button"> <i class="material-icons md-search"></i></button>
            </div>
            <datalist id="search_terms">
                <option value="Products">
                <option value="New orders">
                <option value="Apple iphone">
                <option value="Ahmed Hassan">
            </datalist>
        </form>
    </div>
    <div class="col-nav">
        <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"> <i class="material-icons md-apps"></i> </button>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link btn-icon" href="#">
                    <i class="material-icons md-notifications animation-shake"></i>
                    <span class="badge rounded-pill">3</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
            </li>
            <li class="nav-item">
                <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
            </li>
            <li class="dropdown nav-item">
                <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="{{ request.user.profile.url }}" alt="User"></a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                    <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>{{request.user.email}}</a>
                    <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                    <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                    <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                    <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                    <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{% url 'admin_app:admin_logout' %}"><i class="material-icons md-exit_to_app"></i>Logout</a>
                </div>
            </li>
        </ul>
    </div>
</header>
{% endblock content %}

earc/templates/admin_sidenav.html
{% load static %}

    <div class="screen-overlay"></div>
    <aside class="navbar-aside" id="offcanvas_aside">
        <div class="aside-top">
            <a href="{% url 'admin_app:admin_dashboard' %}" class="brand-wrap">
                <img src="{% load admin_logo_tag %}{% get_logo_url %}" class="logo" alt="Evara Dashboard">
            </a>
            <div>
                <button class="btn btn-icon btn-aside-minimize"> <i class="text-muted material-icons md-menu_open"></i> </button>
            </div>
        </div>
        <nav>
            <ul class="menu-aside">
                <li class="menu-item {% if request.path == '/admin/dashboard/' %} active {% endif %}">
                    <a class="menu-link" href="{% url 'admin_app:admin_dashboard' %}"> <i class="icon material-icons md-home"></i>
                        <span class="text">Dashboard</span>
                    </a>
                </li>
                <li class="menu-item {% if request.path == '/admin/products/category/' %} active {% endif %}">
                    <a class="menu-link" href="{% url 'admin_product_app:admin_category' %}"> <i class="icon material-icons md-home"></i>
                        <span class="text">Category</span>
                    </a>
                </li>
                <li class="menu-item has-submenu {% if 'products/brands' in request.path %} active {% endif %}">
                    <a class="menu-link" > <i class="icon material-icons md-shopping_bag"></i>
                        <span class="text">Brand</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'admin_product_app:list_brands' %}" class="{% if request.path == '/admin/products/brands/' %} active fw-bold {% endif %}">Brand List</a>
                        <a href="{% url 'admin_product_app:add_brand' %}" class="{% if request.path == '/admin/products/brands/add/' %} active fw-bold {% endif %}">Add brand</a>
                    </div>
                </li>
                <li class="menu-item has-submenu {% if 'list' in request.path or '/products/add/' in request.path %} active {% endif %}">
                    <a class="menu-link" > <i class="icon material-icons md-shopping_bag"></i>
                        <span class="text">Products</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'admin_product_app:list_products' %}" class="{% if request.path == '/admin/products/list/' %} active fw-bold {% endif %}">Product List</a>
                        <a href="{% url 'admin_product_app:add_product' %}" class="{% if request.path == '/admin/products/add/' %} active fw-bold {% endif %}">Add product</a>
                    </div>
                </li>
                <li class="menu-item has-submenu {% if 'banner' in request.path %} active {% endif %}">
                    <a class="menu-link"> <i class="icon material-icons md-person"></i>
                        <span class="text">Banner</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'banner_app:list_banner' %}" class="{% if request.path == '/admin/banner/' %} active fw-bold {% endif %}">Banners</a>
                        <a href="{% url 'banner_app:add_banner' %}" class="{% if request.path == '/admin/banner/add/' %} active fw-bold {% endif %}">Add banner</a>
                    </div>
                </li>
                <li class="menu-item has-submenu {% if 'order' in request.path %} active {% endif %}">
                    <a class="menu-link" > <i class="icon material-icons md-shopping_cart"></i>
                        <span class="text">Orders</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'admin_order_app:order_list' %}" class="{% if request.path == '/admin/order/' %} active fw-bold {% endif %}">Order list</a>
                        <a href="page-orders-2.html">Order list 2</a>
                        <a href="page-orders-detail.html">Order detail</a>
                    </div>
                </li>
                <li class="menu-item has-submenu {% if 'coupen' in request.path %} active {% elif 'offers' in request.path %} active {% endif %}">
                    <a class="menu-link"> <i class="icon material-icons md-monetization_on"></i>
                        <span class="text">Offers</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'admin_coupen_app:list_coupens' %}" class="{% if request.path == '/admin/coupen/' %} active fw-bold {% endif %}">Coupens Offers</a>
                        <a href="{% url 'admin_offer_app:list_category' %}" class="{% if request.path == '/admin/offers/category/' or request.path == '/admin/offers/category/add/' %} active fw-bold {% endif %}">Category offers</a>
                        <a href="{% url 'admin_offer_app:list_brand' %}" class="{% if request.path == '/admin/offers/brand/' or request.path == '/admin/offers/brand/add/' %} active fw-bold {% endif %}">Brand offers</a>
                    </div>
                </li>
                <li class="menu-item has-submenu {% if 'top_sellings' in request.path %} active {% endif %}">
                    <a class="menu-link" href=""> <i class="icon material-icons md-store"></i>
                        <span class="text">Top sellings</span>
                    </a>
                    <div class="submenu">
                        <a class="{% if 'category' in request.path %} active fw-bold {% endif %}" href="{% url 'admin_app:top_sellings' %}?item='category' ">Category</a>
                        <a class="{% if request.path in 'brand' %} active fw-bold {% endif %}" href="{% url 'admin_app:top_sellings' %}?item='brand' ">Brand</a>
                        <a class="{% if request.path in 'product' %} active fw-bold {% endif %}" href="{% url 'admin_app:top_sellings' %}?item='product' ">Product</a>
                    </div>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link"> <i class="icon material-icons md-monetization_on"></i>
                        <span class="text">Transactions</span>
                    </a>
                    <div class="submenu">
                        <a href="page-transactions-1.html">Transaction 1</a>
                        <a href="page-transactions-2.html">Transaction 2</a>
                    </div>
                </li>
                <li class="menu-item has-submenu {% if 'user' in request.path %} active {% endif %}">
                    <a class="menu-link"> <i class="icon material-icons md-person"></i>
                        <span class="text">Account</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'admin_app:load_table' %}" class="{% if request.path == '/admin/users/' %} active {% endif %}">Users</a>
                        <a href="{% url 'user_app:user_login' %}">User login</a>
                        <a href="{% url 'user_app:user_registration' %}">User registration</a>
                        <a href="{% url 'user_app:fournoterror' %}">Error 404</a>
                    </div>
                </li>
                <li class="menu-item">
                    <a class="menu-link"> <i class="icon material-icons md-comment"></i>
                        <span class="text">Reviews</span>
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" disabled> <i class="icon material-icons md-pie_chart"></i>
                        <span class="text">Statistics</span>
                    </a>
                </li>
            </ul>
            <hr>
            <ul class="menu-aside">
                <li class="{% if request.path == '/admin/settings/' %} active {% endif %} menu-item has-submenu">
                    <a href="{% url 'admin_app:site_settings' %}"  class=""> <i class="icon material-icons md-settings"></i>
                        <span class="text">Settings</span>
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link"> <i class="icon material-icons md-local_offer"></i>
                        <span class="text"> Starter page </span>
                    </a>
                </li>
            </ul>
            <br>
            <br>
        </nav>
    </aside>

earc/templates/user_navbar.html
{% load static %}
{% load cart_tags %}

<style>
    .header-area {
        background-color: #f8f9fa;
    }
    .header-info ul {
        list-style: none;
        padding: 0;
        margin: 0;
    }
    .header-info ul li {
        display: inline;
        margin-right: 15px;
    }
    .header-middle {
        background-color: white;
        color: #fff;
    }
    .header-middle a {
        color: #fff;
    }
    .header-middle .search-box input {
        border-radius: 10px;
        border: 1px solid #ced4da;
    }
    .header-middle .search-box .search-button {
        border-radius: 10px;
        border: 1px solid #ced4da;
    }
    .header-middle .btn-primary {
        border-radius: 0;
    }
    .header-bottom {
        background-color: #ffffff;
        border-top: 1px solid #dee2e6;
    }
    .navbar-nav .nav-link {
        color: #343a40;
        font-weight: bold;
    }
    .navbar-nav .nav-link:hover {
        color: #088178;
    }
    .cart-dropdown-wrap {
        width: 300px;
    }
    .shopping-cart-footer {
        padding: 10px;
        background-color: #f8f9fa;
    }
    .shopping-cart-total h4 {
        margin: 0;
        font-size: 14px;
    }
    @media (min-width: 992px) {
        .navbar-nav {
            display: flex;
            justify-content: center;
            width: 100%;
        }
    }
</style>

<header class="header-area header-style-1 header-height-2">
    <div class="header-top py-1 d-block" style="background-color: #d8f4e2; border-bottom: 3px solid #39b4ac; padding: 10px 0;">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between py-2">
                <div class="">
                    <div class="header-info">
                        <div class="logo">
                            <a href="{% url 'user_app:user_home' %}"><img style="width: 75px;" src="{% load user_logo_tag %}{% get_logo_url %}" alt="logo"></a>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="header-info text-end">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item dropdown nav-item">
                                <a href="#" id="dropdownAccount">
                                    {% if user.is_authenticated %} 
                                        {% if user.profile %}
                                        <a href="{% url 'user_app:account_view' %}">
                                            <img class="img-xs rounded-circle" src="{{ user.profile.url }}" style="width: 43px; height: 43px;" alt="">
                                        </a>
                                        {% endif %}
                                    {% else %}
                                        <li class="list-inline-item">
                                            <i class="fi-rs-user"></i>
                                            <a class="text-dark" href="{% url 'user_app:user_login' %}">Login</a>   
                                        </li>
                                    {% endif %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-middle py-3 d-block">
        <div class="container">
            <div class="d-flex flex-column align-items-center">
                <div class="d-flex align-items-center w-100" style="border-bottom: 2px solid whitesmoke;">
                    <div style="width: 100%; padding-bottom: 10px;" class="header-right d-flex justify-content-between align-items-center">
                        <div class="search-box">
                            <form action="{% url 'user_product_app:list_products' %}" method="get" class="d-flex">
                                {% csrf_token %}
                                <div style="display: flex;">
                                    <input type="search" name="search_text" class="" placeholder="{% if search %} {{search}} {% elif sort_with_search %} {{sort_with_search}} {% else %} Search  {% endif %}">
                                    <button type="submit" class="btn search-button btn-sm btn-primary ms-2 text-white" style="background: #088178;">search</button>
                                </div>
                            </form>
                        </div>
                        <div class="header-action d-flex align-items-center ms-3">
                            
                                <div class="header-action-icon">
                                    <a href="{% url 'user_product_app:wishlist_view' %}">
                                        <img class="svgInject" style="width: 16px;" alt="Evara" src="{% static 'assets/imgs/theme/icons/icon-heart.svg' %}">
                                    </a>
                                </div>
    
                                <div class="header-action-icon ms-3 d-flex">
                                        <a class="mini-cart-icon" href="{% url 'cart_app:view_cart' %}">
                                            <img alt="Evara" style="width: 16px;" src="{% static 'assets/imgs/theme/icons/icon-cart.svg' %}">
                                        </a>
                                    
                                    {% if request.user.is_authenticated %}
                                    {% latest_two_items request.user as latest_items %}
                                    {% if latest_items %}
                                    <div class="cart-dropdown-wrap cart-dropdown-hm2">
                                        {% for item in latest_items %}
                                        <ul class="list-unstyled">
                                            <li class="d-flex align-items-center py-2">
                                                <div class="me-3">
                                                    <img style="width: 40px;" src="{{ item.product.thumbnail.url }}" alt="">
                                                </div>
                                                <div>
                                                    <p class="mb-0" style="font-size: 13px;">{{ item.product.product_name }}</p>
                                                    <p class="mb-0">x{{item.quantity}}</p>
                                                </div>
                                            </li>
                                        </ul>
                                        {% endfor %}
                                        <div class="shopping-cart-footer">
                                            <div class="shopping-cart-total">
                                                <h4>Total <span>${% sub_total latest_items %}</span></h4>
                                            </div>
                                        </div>
                                    </div>
                                    {% endif %}
                                    {% endif %}
                                </div>
                        </div>
                    </div>
                </div>
                <div class="w-100 d-none d-lg-flex justify-content-lg-center align-items-lg-center">
                    <div class="">
                        <ul class="d-flex" style="padding: 10px 0;">
                            <li class="nav-item">
                                <a style="color: black; font-weight: 600;" class="nav-link active" href="{% url 'user_app:user_home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a style="color: black; font-weight: 600;" class="nav-link" href="{% url 'user_product_app:list_products' %}">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a style="color: black; font-weight: 600;" class="nav-link" href="#">About</a>
                            </li>
                            <li class="nav-item">
                                <a style="color: black; font-weight: 600;" class="nav-link" href="#">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom sticky-bar d-lg-none d-block">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center w-100">
                    <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fa-solid fa-bars"></i></span>
                    </button>
                    <div class="collapse navbar-collapse d-lg-flex justify-content-lg-center" id="navbarNav">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'user_app:user_home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user_product_app:list_products' %}">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="page-contact.html">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</header>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        function toggleNavbar() {
            var width = window.innerWidth;
            var navbarNav = document.getElementById('navbarNav');

            if (width >= 992) {
                // For screens larger than lg, ensure the menu is always shown
                navbarNav.classList.add('show');
            } else {
                // For screens less than lg, collapse the menu
                navbarNav.classList.remove('show');
            }
        }

        // Initial call to set the correct state
        toggleNavbar();

        // Add event listener to handle window resizing
        window.addEventListener('resize', toggleNavbar);
    });
</script>