earc/checkout_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'checkout_app'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('place_order/', place_order, name='place_order'),
    path('history/', order_history, name='order_history'),
    path('details/<int:id>/', order_details, name='order_details'),
    path('cancel/<str:action>/<int:id>/', cancel_order, name='cancel_order'),
    path('rate/', rate_review, name='rate_review'),
    path('placed/', order_placed, name='order_placed'),
    path('remove_coupon/', remove_coupon, name='remove_coupon'),
    path('replace/<int:id>/', order_replacement, name='order_replacement'),
    path('return/<int:id>/', return_and_refund, name='return_and_refund'),
    path('payment_authorization/', razorpay_order, name='razorpay_order' ),
    path('invoice/<int:id>/', invoice_details, name='invoice_details')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/earc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ============Direction django default admin panel=======
    path('django_admin/', admin.site.urls),

    # ========Direction to admin_app====================
    path('admin/', include('admin_app.urls', namespace='admin_app')),

    # ========Direction to admin_products_app==========
    path('admin/products/', include('admin_product_app.urls', namespace='admin_product_app')),

    # ===========Direction to banner_app===============
    path('admin/banner/', include('banner_app.urls', namespace='banner_app')),

    # ==============Direction to admin_order_app================
    path('admin/order/', include('admin_order_app.urls', namespace='admin_order_app')),

    # ===================Direction to admin_coupen_app=========================
    path('admin/coupen/', include('admin_coupen_app.urls', namespace='admin_coupen_app')),

    # ============Direction to offer_app========================
    path('admin/offers/', include('offer_app.urls', namespace='admin_offer_app')),

    #===========Direction to user_app=================
    path('', include('user_app.urls', namespace='user_app')),

    #===========Direction to user_product_app=========
    path('products/', include('user_product_app.urls', namespace='user_product_app')),

    # ============Direction to cart_management=======================
    path('cart/', include('cart_app.urls', namespace='cart_app')),


    # =============Direction to checkout_app======================
    path('checkout/', include('checkout_app.urls', namespace='checkout_app')),

    


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/user_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

 
app_name = 'user_app'

urlpatterns = [
    path('', user_home, name='user_home'),
    path('register/', user_registration , name='user_registration'),
    path('otp/', otp_checking, name='otp_checking'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('resent_otp/', otp_resent, name='otp_resent'),
    path('404error/', fournoterror, name='fournoterror'),
    path('email/', forget_password_user_conform, name='forget_password_user_conform'),
    path('forget_otp/', sent_forget_password_otp, name='sent_forget_password_otp'),
    path('forget_password/', forget_password, name='forget_password'),
    path('change_password/', change_password, name='change_password'),
    path('account/', account_view, name='account_view'),
    path('user/', update_password, name='update_password'),
    path('details/<int:id>/', update_details, name='update_details'),
    path('address/', add_address, name='add_address'),
    path('address/<int:id>/', update_address, name='update_address'),
    path('delete_address/<int:id>/', delete_address, name='delete_address'),
    path('wallet/', wallet_view, name='wallet_view')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

earc/user_product_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

 
app_name = 'user_product_app'


urlpatterns = [
    path('', product_list, name='list_products'),
    path('view/<int:id>/', product_view, name='product_view'),
    path('view/<int:id>/get_details/<int:colorId>/', collect_image, name='collect_image'),
    path('wishlist/', wishlist_management.wishlist_view, name='wishlist_view'),
    path('add_wishlist/<int:id>/', wishlist_management.add_wishlist_item, name='add_wishlist_item'),
    path('remove_wishlist_item/<int:p_id>/<int:c_id>/<int:s_id>/', wishlist_management.remove_from_wishlist, name='remove_from_wishlist'),
    path('quantity_check/', quantity_check, name='quantity_check'),
    path('movetocart/', wishlist_management.move_to_cart, name='move_to_cart')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

earc/templates/user_template/add_address.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Add address
{% endblock %}
{% block content %}

<main class="main">
    {% include 'user_navbar.html' %}
    <section>
        <div style="width: 100%; height: fit-content; display: flex; justify-content: center; align-items: center;">
            <div style="width: 50%; height: fit-content; display: flex; flex-direction: column;">
                <div style="width: 100%; padding: 10px 20px; background: whitesmoke;">
                    <h5 class="fw-bold">Delivary address</h5>
                </div>
                <div style="width: 100%; padding: 10px 20px" class="mt-3">
                    <!-- ========== Start user or phone number messages ========== -->
                        {% if messages %}
                        {% for message in messages %}
                            <p class="text-danger fw-semibold fs-6">{{ message }}</p>
                        {% endfor %}
                        {% endif %}
                    <!-- ========== End user or phone number messages ========== -->
                    <form method="post" {% if address_obj %} action="{% url 'user_app:update_address' id=address_obj.address_id %}?next={{request.path}}" {% endif %} enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <!-- name -->
                            <div class="col-12">
                                <div data-mdb-input-init class="form-outline">
                                    <label class="form-label" for="form7Example1">Name</label>
                                    <input type="text" id="form7Example1" class="form-control" name="name" value="{{ address_obj.name }}"/>
                                </div>
                            </div>

                            <div data-mdb-input-init class="row form-outline mt-3">
                                <div class="col-6">
                                    <label style="text-align: center;" for="">Home</label>
                                    <input type="radio" value="Home" name="address_type">
                                </div>
                                <div class="col-6">
                                    <label style="text-align: center;" for="">Office</label>
                                    <input type="radio" value="Office" name="address_type">
                                </div>
                            </div>
            
                            <!-- Text input -->
                            <div data-mdb-input-init class="col-12 form-outline mt-3">
                                <label class="form-label" for="form7Example3">Company or Home name</label>
                                <input type="text" id="form7Example3" class="form-control" value="{{address_obj.building_name}}" name="building_name"/>
                            </div>

                            <!-- Number input -->
                            <div data-mdb-input-init class="row-outline mt-3">
                                <div class="col-12">
                                    <select name="country_code">
                                        <!-- Populate the dropdown with country options dynamically -->
                                        <option value="">Select Country</option>
                                        {% for country_code, country_name in COUNTRY_CHOICES %}
                                            <option value="{{ country_code }}">{{ country_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12">
                                    <label class="form-label" for="form7Example6">Phone</label>
                                    <input type="text" id="form7Example6" class="form-control" value="{{address_obj.phone}}" name="phone"/>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-6">
                                    <div data-mdb-input-init class="col-12 -outline mt-3">
                                        <label class="form-label" for="form7Example6">State</label>
                                        <input type="text" id="form7Example6" class="form-control" value="{{address_obj.state}}" name="state"/>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div data-mdb-input-init class="col-12 -outline mt-3">
                                        <label class="form-label" for="form7Example6">City</label>
                                        <input type="text" id="form7Example6" class="form-control" value="{{address_obj.city}}" name="city"/>
                                    </div>
                                </div>
                            </div>

                            <div data-mdb-input-init class="col-12 -outline mt-3">
                                <label class="form-label" for="form7Example6">Pincode</label>
                                <input type="text" id="form7Example6" class="form-control" value="{{address_obj.pincode}}" name="pincode"/>
                            </div>

                            <!-- Text input -->
                            <div data-mdb-input-init class="col-12 form-outline mt-3">
                                <label class="form-label" for="form7Example4">Address</label>
                                <input type="text" id="form7Example4" class="form-control" value="{{address_obj.address}}" name="address"/>
                            </div>

                            {% if address_obj %}
                            <div data-mdb-input-init class="col-12 form-outline mt-3">
                                <button class="btn btn-sm btn-primary">Update</button>
                            </div>
                            {% else %}
                            <div data-mdb-input-init class="col-12 form-outline mt-3">
                                <button class="btn btn-sm btn-primary">Submit</button>
                            </div>
                            {% endif %}

                    </form>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

earc/templates/user_template/find_user.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Forgot password 
{% endblock %}
{% block content %}
<main class="main">
    <div style="width: 100%; height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <!-- {% if messages %}
        {% for message in messages %}
        <p id="error" class="text-danger">{{ message }}</p>
        {% endfor %}
        {% endif %} -->
        <p id="error" class="text-danger">{{ message }}</p>
        <div id="image_container" style="display: block;">
            <img id="image" style="width: 110px; height: 110px; border-radius: 100%;" src="{{ user_profile }}" alt="">
        </div>

        
        <div id="form_container" style="margin-top: 28px;" class="w-25">
            <form id="email_form" action="">
                {% csrf_token %}
                <div>
                    <input class="form-control w-100" placeholder="email" type="text" name="email" value="{{ email }}">
                </div>
                <div id="button_container" class="" style="display: block; margin-top: 22px;">
                    <div class="d-grid gap-2">
                        <a
                            name=""
                            id=""
                            class="btn btn-primary"
                            href="{% url 'user_app:sent_forget_password_otp' %}"
                            role="button"
                            >Sent OTP</a
                        >
                        
                    </div>
                    
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

earc/templates/user_template/invoice.html
{% extends "user_base.html" %}
{% load static %}
{% load order_tags %}
{% block title %}
Invoice
{% endblock %}

{% block content %}
<main style="width: 100%; padding: 100px 50px;" class="d-flex flex-column align-order_objs-center">
    <div style="width: 90%; height: fit-content; display: flex; justify-content: space-around; padding-bottom: 150px;">
        <div style="width: 50%; display: flex; flex-direction: column; align-items: center;">
            <div>
                <h1 class="fw-bold" style="color: #088178;">mobileArc</h1>
            </div>
            <div class="">
                <p class="fw-bold" style="font-size: 13px;">Kannur, Kerala, India</p>
            </div>
        </div>
        <div style="width: 50%; display: flex; flex-direction: column; align-items: center;">
            <h4>Invoice
                    {% if order_obj.order_payment.payment_status %}
                    <span class="badge bg-success">Paid</span>
                    {% elif order_obj.status == 5 %}
                    <span class="badge bg-danger">Cancel</span>
                    {% elif order_obj.status == 7 %}
                    <span class="badge bg-danger">Return & Refund</span>
                    {% else %}
                    <span class="badge bg-warning">Pending</span>
                    {% endif %}
            </h4>
            <p class="fw-bold">{{order_obj.order_payment.payment_mode}}</p>

        </div>
    </div>
    <div
        style="width: 90%; height: fit-content; display: flex; justify-content: space-around; padding-bottom: 50px; border-bottom: solid gray 1px;">
        <div style="width: 50%; display: flex; flex-direction: column; align-items: center;">
            <div>
                <h3 class="fw-bold">Billed to:</h3>
                <br>
                <p class="fw-bold">{{order_obj.order_customer.customer.username}}</p>
                <br>
                <p class="fw-bold">{{order_obj.order_address.building_name}}, {{order_obj.order_address.address}}</p>
                <p class="fw-bold">{{order_obj.order_address.city}}, {{order_obj.order_address.state}}, {{order_obj.order_address.pincode}}</p>
            </div>
        </div>
        <div style="width: 50%; display: flex; justify-content: center;">
            <div>
                <h4>Invoice date: <span style="font-size: 15px; margin-left: 10px;">{{order_obj.update_at}}</span></h4>
                <br>
                <h4>Order no: <span style="font-size: 15px; margin-left: 10px;">{{order_obj.cart_id}}</span></h4>
            </div>
        </div>
    </div>

    <div style="width: 90%; height: fit-content; display: flex; justify-content: space-around; padding-bottom: 50px;">
        <div style="width: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; margin-top: 50px;">
            <h3 class="fw-bold">Order summary</h3>
            <div style="width: 70%; margin-top: 40px; display: flex; justify-content: center;">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Price</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="fw-bold">Price</td>
                        <td>{% product_with_storage_price order_obj %}</td>
                        <td>{{order_obj.quantity}}</td>
                        <td>{% product_price order_obj %} <span class="text-success fw-bold">+</span></td>
                      </tr> 
                      <tr>
                        <td class="fw-bold">Discount</td>
                        <td>{% discount_price order_obj %}</td>
                        <td>{{ order_obj.quantity }}</td>
                        <td>{% total_discount_price order_obj %}<span class="text-danger fw-bold">-</span></td>
                      </tr>
                      <tr>
                        <td class="fw-bold">Coupon</td>
                        <td>{{order_obj.coupon_amount}}</td>
                        <td>1</td>
                        <td>{{order_obj.coupon_amount}} <span class="text-danger fw-bold">-</span></td>
                      </tr>
                      <tr>
                        <td class="fw-bold">Shiping</td>
                        <td>{{order_obj.delivery_charge}}</td>
                        <td>1</td>
                        <td>{{order_obj.delivery_charge}} <span class="text-success fw-bold">+</span></td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td class="fw-bold">Grand total</td>
                        <td>{% grand_total order_obj %}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
        </div>
    </div>

    <div style="margin-top: 20px;">
        <a href="javascript:window.print()" class="btn btn-success me-1"><i class="fa fa-print"></i></a>
    </div>






</main>
{% endblock %}

earc/templates/user_template/order_conform_page.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Order conform
{% endblock %}
{% block content %}
<main class="main">
    {% include 'user_navbar.html' %}
    <div id="order_conform_section" style="width: 100%; height: 100vh; background-color: #088178;">
        <div style="width: 100%; height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center;">
            <div>
                <h3 class="text-white">Thanks for order {{username}}</h3>
            </div>
            <div class="mt-4">
                <img src="{% static 'assets/imgs/shop/order_placed_animation-ezgif.com-speed.gif' %}" alt="">
            </div>
            <div>
                <h4 class="text-white fw-bold">Your oder Succesfully placed</h4>
            </div>
            <div class="gap-3 mt-4" style="display: flex;">
                <a style="background: white; color: #088178;" href="{% url 'checkout_app:order_history' %}" class="btn btn-sm">Check order</a>
                <a style="background: white; color: #088178;" href="{% url 'user_product_app:list_products' %}" class="btn btn-sm">Continue Shoping</a>
            </div>
        </div>
    </div>
    
</main>
{% endblock %}

earc/templates/user_template/otp-email.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Forgot password 
{% endblock %}
{% block content %}
<main class="main">
    <div style="width: 100%; height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <!-- {% if messages %}
        {% for message in messages %}
        <p id="error" class="text-danger">{{ message }}</p>
        {% endfor %}
        {% endif %} -->
        <p id="error" class="text-danger">{{ message }}</p>
        <div id="image_container" style="display: none;">
            <img id="image" style="width: 110px; height: 110px; border-radius: 100%;" src="" alt="">
        </div>

        <div id="button_container" class="" style="display: none; margin-top: 22px;">
            <div class="d-grid gap-2">
                <a
                    name=""
                    id=""
                    class="btn btn-primary"
                    href="{% url 'user_app:sent_forget_password_otp' %}"
                    role="button"
                    >Sent OTP</a
                >
                
            </div>
            
        </div>
        <div id="form_container" style="margin-top: 28px;" class="w-25">
            <form id="email_form" action="">
                {% csrf_token %}
                <div>
                    <input class="form-control w-100" placeholder="email" type="text" name="email">
                </div>
                <input type="submit" class="btn btn-primary w-100 mt-2">
            </form>
        </div>
    </div>
</main>


<script>
    const imageContainer = document.getElementById('image_container')
    const image = document.getElementById('image')
    const error = document.getElementById('error')
    const formContainer = document.getElementById('form_container')
    const buttonContainer = document.getElementById('button_container')

    document.getElementById('email_form').addEventListener('submit', function(event){
        event.preventDefault();

        const formData = new FormData(this)
        fetch('', {
            method:'POST',
            body:formData
        })
        .then(response => response.json())
        .then(data => {
            if(data.status == 'success'){
                imageContainer.style.display = 'block'
                image.src = data.user_profile
                formContainer.style.display = 'none'
                buttonContainer.style.display = 'block'
            }else{
                buttonContainer.style.display = 'none'
                imageContainer.style.display = 'none'
                error.innerHTML = data.text
            }
            
        }).catch(error => {
            error.innerHTML = 'something wrong!'
        })
    })

</script>
{% endblock %}

earc/templates/user_template/page-404.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
    <main class="main page-404">
        <div class="container">
            <div class="row align-items-center height-100vh text-center">
                <div class="col-lg-8 m-auto">
                    <p class="mb-50"><img src="{% static 'assets/imgs/theme/404.png' %}" alt="" class="hover-up"></p>
                    <h2 class="mb-30">Page Not Found</h2>
                    <p class="font-lg text-grey-700 mb-30">
                        The link you clicked may be broken or the page may have been removed.<br> visit the <a href="{% url 'user_app:user_home' %}"> <span> Homepage</span></a> or <a href="{% url 'user_app:user_home' %}"><span>Contact us</span></a> about the problem
                    </p>
                    <form class="contact-form-style text-center" id="contact-form" action="#" method="post">
                        <div class="row">
                            <div class="col-lg-6 m-auto">
                                <div class="input-style mb-20 hover-up">
                                    <input name="name" placeholder="Search" type="text">
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-default submit-auto-width font-xs hover-up" href="{% url 'user_app:user_home' %}">Back To Home Page</a>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="text-center">
                    <h5 class="mb-5">Now Loading</h5>
                    <div class="loader">
                        <div class="bar bar1"></div>
                        <div class="bar bar2"></div>
                        <div class="bar bar3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

earc/templates/user_template/wallet.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
<main class="main">
    {% include 'user_navbar.html' %}
    <div style="width: 100%; height: fit-content; display: flex; justify-content: center; padding: 30px 0px;">
        <div style="width: 80%; display: flex; flex-direction: column; align-items: center;">
            <div style="padding: 20px;">
                <h2 class="fw-bold text-success"><span class="me-2"><i class="fa-solid fa-indian-rupee-sign"></i></span>{{wallet_obj.balance}}</h2>
            </div>
            <div style="padding: 50px;">
                <a class="btn btn-lg btn-primary">Sent to bank</a>
            </div>
            <div style="width: 100%; display: flex; justify-content: center;">
                <div style="width: 50%;">
                    {% for item in wallet_history_obj %}
                    <div class="row" style="padding: 10px 15px; border-top: solid black 1px; border-bottom: solid black 1px;">
                        <div class="col-10 gap-1" style="padding: 7px; display: flex; flex-direction: column;">
                            <h5 class="fw-bold">{{item.order_item.product.product_name}}</h5>
                            <p style="font-size: 13px; color: rgb(91, 91, 91);" class="fw-bold">{{item.created_at|date:"d/m/y g:i A"}}</p>
                        </div>
                        <div class="col-2 d-flex align-items-center" >
                            {% if item.status == 'Credit' %}
                            <p class=" text-success fw-bold">+{{item.amount}}</p>
                            {% else %}
                            <p class=" text-danger fw-bold">-{{item.amount}}</p>
                            {% endif %} 
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}