earc/admin_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

 
app_name = 'admin_app'

urlpatterns = [
    # =============Login and Logout===============
    path('login/', admin_login, name='admin_login'),
    path('logout/', admin_logout, name='admin_logout'),
    # =============Login and Logout===============

    # ==============Dashboard=====================
    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('get_chart_data/', get_chart_data, name='get_chart_data'),
    # =============Dashboard=======================

    # ==============Crud oprations=======================
    path('users/get_user', get_user, name="get_user"),
    path('users/delete/<int:id>/', user_crud_view.delete, name='delete_user'),
    path('users/', user_crud_view.load_table, name='load_table'),
    path('users/blocked/', user_crud_view.blocked_users, name='blocked_users'),
    path('user/create', user_crud_view.create_user, name='create_user'),
    path('user/<int:id>/update', user_crud_view.update_user, name='update_user'),
    path('user/<int:id>/block', user_crud_view.block_user, name='block_user'),
    path('user/<int:id>/unblock', user_crud_view.unblock_user, name='unblock_user'),
    path('sales_report/', sales_report, name='sales_report'),
    # ==============Crud oprations=======================

    #===============Settings===========================
    path('settings/', site_settings, name='site_settings'),
    path('logo/', logo, name='logo'),

    path('top_sellings/', top_sellings, name='top_sellings')
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/admin_product_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

 
app_name = 'admin_product_app'

urlpatterns = [
    # ===============Products========================
    path('list/', product_management.list_products, name='list_products'),
    path('add/', product_management.add_product, name='add_product'),
    path('add/getbrands/<str:brand_name>/', get_category, name='get_category_product_adding'),   
    path('edit/<int:id>/', product_management.update_product, name='update_product'),
    path('delete_product/<int:id>/', product_management.delete_product, name='delete_product'),
    path('edit/<int:id>/get_category/<str:brand_name>/', get_category, name='get_category'),
    path('item/<str:action>/<int:id>/', product_management.block_and_unblock, name='product_block_and_unblock'),   
    path('stock/<int:id>/', product_management.stock_view, name='stock_view'),

    # ==============Brands=======================
    path('brands/', brand_management.brands, name='list_brands'),
    path('brands/add/', brand_management.add_brand, name='add_brand'),
    path('brands/<str:action>/<int:id>/', brand_management.block_and_unblock, name='brand_block_and_unblock'),
    path('brand/<int:id>', brand_management.update_brand, name='update_brand'),
    path('brand/del/<int:id>/', brand_management.delete_brand, name='delete_brand'),

    # ==========Category=================
    path('category/', category_management.category, name='admin_category'),
    path('<int:id>/', category_management.delete_category, name='delete_category'),
    path('category/<int:id>/', category_management.update_category, name='update_category'),
    path('category/<str:action>/<int:id>/', category_management.block_and_unblock, name='category_block_and_unblock'),

    # ============Variations==============
    path('variants/<int:id>/', variant_management.list_variant, name='list_variant'),
    path('variant/<int:id>/', variant_management.add_color_variant, name='add_variant'),
    path('varinat/<int:product_id>/<int:id>/', variant_management.add_storage_variant, name='add_storage_variant'),
    path('view/<int:id>/', variant_management.variant_detailed_view, name='variant_detailed_view'),
    path('image/<int:id>/', variant_management.add_variant_image, name='add_varient_image'),
    path('delete_image/<int:image_id>/<int:id>/', variant_management.delete_image, name='delete_image'),
    path('change_image/<int:image_id>/<int:id>/', variant_management.change_image, name='change_image'),
    path('delete_variant/<int:product_id>/<int:id>/', variant_management.delete_color, name='delete_color'),
    path('getcolorname/<int:id>/', variant_management.get_color_name, name='get_color_name'),
    path('size/<int:id>/', variant_management.update_storage, name='edit_storage'),
    path('storage/<str:action>/<int:id>/', variant_management.delete_storage, name='delete_storage')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/checkout_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'checkout_app'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('place_order/', place_order, name='place_order'),
    path('history/', order_history, name='order_history'),
    path('details/<int:id>/', order_details, name='order_details'),
    path('cancel/<str:action>/<int:id>/', cancel_order, name='cancel_order'),
    path('rate/', rate_review, name='rate_review'),
    path('placed/', order_placed, name='order_placed'),
    path('remove_coupon/', remove_coupon, name='remove_coupon'),
    path('replace/<int:id>/', order_replacement, name='order_replacement'),
    path('return/<int:id>/', return_and_refund, name='return_and_refund'),
    path('payment_authorization/', razorpay_order, name='razorpay_order' ),
    path('invoice/<int:id>/', invoice_details, name='invoice_details')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/earc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ============Direction django default admin panel=======
    path('django_admin/', admin.site.urls),

    # ========Direction to admin_app====================
    path('admin/', include('admin_app.urls', namespace='admin_app')),

    # ========Direction to admin_products_app==========
    path('admin/products/', include('admin_product_app.urls', namespace='admin_product_app')),

    # ===========Direction to banner_app===============
    path('admin/banner/', include('banner_app.urls', namespace='banner_app')),

    # ==============Direction to admin_order_app================
    path('admin/order/', include('admin_order_app.urls', namespace='admin_order_app')),

    # ===================Direction to admin_coupen_app=========================
    path('admin/coupen/', include('admin_coupen_app.urls', namespace='admin_coupen_app')),

    # ============Direction to offer_app========================
    path('admin/offers/', include('offer_app.urls', namespace='admin_offer_app')),

    #===========Direction to user_app=================
    path('', include('user_app.urls', namespace='user_app')),

    #===========Direction to user_product_app=========
    path('products/', include('user_product_app.urls', namespace='user_product_app')),

    # ============Direction to cart_management=======================
    path('cart/', include('cart_app.urls', namespace='cart_app')),


    # =============Direction to checkout_app======================
    path('checkout/', include('checkout_app.urls', namespace='checkout_app')),

    


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/offer_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'admin_offer_app'

urlpatterns = [
    # Category offers
    path('category/', list_category, name='list_category'),
    path('category/add/', add_category_offer, name='add_category_offer'),
    path('category/block_unblock/<int:id>/', block_unblock_category, name='block_unblock_category'),
    path('category/update/<int:id>/', update_category_offer, name='update_category_offer'),
    path('category/details/<int:id>/', category_offer_details, name='category_offer_details'),

    # Brand offers
    path('brand/', list_brand, name='list_brand'),
    path('brand/add/', add_brand_offer, name='add_brand_offer'),
    path('brand/block_unblock/<int:id>/', block_and_unblock_brand, name='block_and_unblock_brand'),
    path('brand/update/<int:id>/', update_brand_offer, name='update_brand_offer'),
    path('brand/details/<int:id>/', brand_details, name='brand_details')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earc/templates/admin_template/blocked_users.html
{% extends "base_page.html" %}
{% load static %}

{% block title %}
Users
{% endblock %}


{% block content %}

{% include "admin_sidenav.html"%}

  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg main-wrap">
    {% include 'admin_nav.html' %}

    <div class="container-fluid py-4">
      <div class="row px-0">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3 d-flex justify-content-between align-items-center">
                        <h6 class="text-dark text-capitalize ps-3">Blocked Users</h6>
                        <a href="{% url 'admin_app:load_table' %}" class="btn btn-success text-white">Active Users</a>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center">
                            <thead>
                                <tr class="">
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Users</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">block & unblock</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for u in user %}
                                {% if not u.is_active %}
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div>
                                              {% if u.profile %}
                                              <img src="{{ u.profile.url }}" class="rounded-circle shadow-4 avatar avatar-sm me-3 border-radius-lg"
                                              style="width: 40px; height: 40px;" alt="" />
                                              {% else %}
                                                <img src="{% static 'assets2/imgs/default.jpg' %}" class="rounded-circle shadow-4 avatar avatar-sm me-3 border-radius-lg" 
                                                style="width: 40px; height: 40px;" alt="" >
                                              {% endif %}
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">{{ u.username }}</h6>
                                                <p class="text-xs text-secondary mb-0">{{ u.email }}</p>
                                            </div>
                                        </div>
                                    </td>

                                    <td class="align-middle text-center text-sm">
                                        <span class="fw-bold {% if u.is_active %} text-success {% else %} text-danger {% endif %} ">
                                          {% if u.is_active %}
                                            Active
                                          {% else %}
                                            Block
                                          {% endif %}
                                        </span>
                                    </td>
                                    
                                    <td class="align-middle">
                                        {% if u.is_active %}
                                        <a href="{% url 'admin_app:block_user' id=u.user_id %}" class="text-white btn btn-dark btn-xs text-secondary text-xs">
                                            Block
                                        </a>
                                        {% else %}
                                        <a href="{% url 'admin_app:unblock_user' id=u.user_id %}" class="text-white btn btn-secondary btn-xs text-secondary text-xs">
                                            Unblock
                                        </a>
                                        {% endif %}
                                    </td>
                                    
                                    <td class="align-middle">
                                        <a href="{% url 'admin_app:delete_user' id=u.user_id %}" class="text-white btn btn-danger btn-xs text-xs">
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
  </main>
  
{% endblock content %}

earc/templates/admin_template/change_varinat_image.html
{% extends "base_page.html" %}
{% load static %}

{% block title %}
ADD PRODUCT
{% endblock %}


{% block content %}
{% include "admin_sidenav.html"%}

    <main class="main-wrap">
        {% include 'admin_nav.html' %}

        <section class="content-main">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="row justify-content-center">
                
                <div class="col-6">
                    <div class="d-flex justify-content-between">
                        <h2 class="fs-5">Change image</h2>
                        <div>
                            <!-- <button class="btn btn-light rounded font-sm mr-5 text-body hover-up">Save to draft</button> -->
                            <button type="submit" class="btn btn-md rounded font-sm hover-up">Publich</button>
                        </div>
                    </div>
                </div>
            

                <div class="row justify-content-center mt-4">
                    <div class="col-lg-6">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Image</h4>
                            </div>
                            <div class="card-body">
                                {% if messages %}
                                {% for message in messages %}
                                    <p class="text-danger fw-semibold fs-6">{{ message }}</p>
                                {% endfor %}
                                {% endif %}
                                <div class="row gx-2 col-12 mt-4">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            <h4>Media</h4>
                                        </div>
                                        <div class="card-body">
                                            <div class="input-upload">
                                                <img src="{{target_image.product_image.url}}" id="variant_img" alt="">
                                                <input class="form-control" type="file" id="upload_image" name="select_image">
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                            </div> <!-- card end// -->
                            <!-- card end// -->
                        </div>
                    </div>
                        
                </div>
            </div>
            
                
            
        </form>
        </section> 
    </main>

    <script>
        const variant_img = document.getElementById('variant_img')
        const upload_image = document.getElementById('upload_image')

        upload_image.addEventListener('change', function() {
            if (upload_image.files[0]) {
                const reader = new FileReader()

                reader.onload = function(e) {
                    variant_img.src = e.target.result
                }

                reader.readAsDataURL(upload_image.files[0])
            }
        })
    </script>
{% endblock content %}

earc/templates/admin_template/offer_list.html
{% extends "base_page.html" %}
{% load static %}

{% block title %}
Oders
{% endblock %}


{% block content %}

{% include 'admin_sidenav.html' %}
    
    <main class="main-wrap">
        {% include 'admin_nav.html' %}
        
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">
                        {% if request.path == '/admin/offers/category/' %}
                            Category offers
                        {% elif request.path ==  '/admin/offers/brand/' %}
                            Brand offers
                        {% endif %}
                    </h2>
                </div>
                <div>
                    {% if request.path == '/admin/offers/category/' %}
                        <a href="{% url 'admin_offer_app:add_category_offer' %}" class="btn btn-sm btn-primary fw-semibold">New Offer</a>
                    {% elif request.path ==  '/admin/offers/brand/' %}
                        <a href="{% url 'admin_offer_app:add_brand_offer' %}" class="btn btn-sm btn-primary fw-semibold">New Offer</a>
                    {% endif %}
                </div>
            </div>
            <div class="card mb-4">
                <header class="card-header">
                    <div class="row gx-3">
                        <div class="col-lg-4 col-md-6 me-auto">
                            <input type="text" placeholder="Search..." class="form-control">
                        </div>
                        <div class="col-lg-2 col-6 col-md-3">
                            <select class="form-select">
                                <option>Status</option>
                                <option>Active</option>
                                <option>Disabled</option>
                                <option>Show all</option>
                            </select>
                        </div>
                        <div class="col-lg-2 col-6 col-md-3">
                            <select class="form-select">
                                <option>Show 20</option>
                                <option>Show 30</option>
                                <option>Show 40</option>
                            </select>
                        </div>
                    </div>
                </header> <!-- card-header end// -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Eligible price</th>
                                    <th scope="col">Discount percentage</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Expire</th>
                                    <th scope="col" class="text-end"> Details </th>
                                </tr>
                            </thead>
                            <tbody>
                               <!-- Table for category offer -->
                                {% if request.path == '/admin/offers/category/' %}
                                    {% for item in offer_items %}
                                        <tr>

                                            <!-- name -->
                                            <td>
                                                <b class="fw-bold" style="font-size: 14px;">{{item.offer_category.category_name}}</b>
                                            </td>

                                            
                                            <!-- price -->
                                            <td>
                                                <p class="fw-bold" style="font-size: 14px;">{{item.eligible_price}}</p>
                                            </td>

                                            <!-- condition -->
                                            <td>
                                                <p class="fw-bold" style="font-size: 14px;">{{item.discount_percentage}}%</p>
                                            </td>

                                            <!-- status -->
                                            <td class="">
                                                <a href="{% url 'admin_offer_app:block_unblock_category' id=item.offer_id %}" class="fw-bold badge rounded-pill {% if item.is_active %} alert-success {% else %} alert-danger {% endif %}">
                                                    {% if item.is_active %}
                                                    Active
                                                    {% else %}
                                                    Block
                                                    {% endif %}
                                                </a>
                                            </td>

                                            <!-- Expire status -->
                                            <td class="">
                                                <p class="fw-bold">{{item.expiration_date}}</p>
                                            </td>

                                            <!-- Details button -->
                                            <td class="text-end">
                                                <a href="{% url 'admin_offer_app:category_offer_details' id=item.offer_id %}" class="btn btn-md rounded font-sm me-2">Detail</a>
                                                <a href="{% url 'admin_offer_app:update_category_offer' id=item.offer_id %}" class="btn btn-md rounded font-sm me-2">Update</a>
                                                <a href="" class=""><i class="fa-solid fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}                                
                                {% elif request.path ==  '/admin/offers/brand/' %}
                                    {% for item in offer_items %}
                                        <tr>
                                            <!-- name -->
                                            <td>
                                                <b class="fw-bold" style="font-size: 14px;">{{item.brand.brand_name}}</b>
                                            </td>

                                            <!-- price -->
                                            <td>
                                                <p class="fw-bold" style="font-size: 14px;">{{item.eligible_price}}</p>
                                            </td>

                                            <!-- condition -->
                                            <td>
                                                <p class="fw-bold" style="font-size: 14px;">{{item.discount_percentage}}%</p>
                                            </td>

                                            <!-- status -->
                                            <td class="">
                                                <a href="{% url 'admin_offer_app:block_and_unblock_brand' id=item.offer_id %}" class="fw-bold badge rounded-pill {% if item.is_active %} alert-success {% else %} alert-danger {% endif %}">
                                                    {% if item.is_active %}
                                                    Active
                                                    {% else %}
                                                    Block
                                                    {% endif %}
                                                </a>
                                            </td>

                                            <!-- Expire status -->
                                            <td class="">
                                                <p class="fw-bold">{{item.expiration_date}}</p>
                                            </td>

                                            <!-- Details button -->
                                            <td class="text-end">
                                                <a href="{% url 'admin_offer_app:brand_details' id=item.offer_id %}" class="btn btn-md rounded font-sm me-2">Detail</a>
                                                <a href="{% url 'admin_offer_app:update_brand_offer' id=item.offer_id %}" class="btn btn-md rounded font-sm me-2">Update</a>
                                                <a href="" class=""><i class="fa-solid fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                               
                            </tbody>
                        </table>
                    </div> <!-- table-responsive //end -->
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            <div class="pagination-area mt-15 mb-50">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-start">
                        <!-- {% if order_data.has_previous %} -->
                        <li class="page-item">
                            <a class="page-link" href="?page={{order_data.previous_page_number}}">
                                <i class="fi-rs-angle-double-small-left"> << </i>
                            </a>
                        </li>
                        <!-- {% endif %} -->

                        <!-- {% for num in order_data.paginator.page_range %} -->
                        <li class="page-item active" id="page_{{num}}">
                            <a class="page-link" href="?page={{num}}">{{num}}</a>
                        </li>
                        <!-- {% endfor %} -->

                        <!-- {% if order_data.has_next %} -->
                        <li class="page-item">
                            <a class="page-link" href="?page={{order_data.next_page_number}}">
                                <i class="fi-rs-angle-double-small-right"> >> </i> 
                            </a>
                        </li>
                        <!-- {% endif %} -->
                    </ul>
                </nav>
            </div>
        </section> <!-- content-main end// -->
        <footer class="main-footer font-xs">
            <div class="row pb-30 pt-15">
                <div class="col-sm-6">
                    <script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>
                    document.write(new Date().getFullYear())
                    </script> ©, Evara - HTML Ecommerce Template .
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-end">
                        All rights reserved
                    </div>
                </div>
            </div>
        </footer>
    </main>
  {% endblock %}

earc/templates/admin_template/page-error-404.html
{% extends "base_page.html" %}
{% load static %}

{% block title %}
Error
{% endblock %}


{% block content %}


{% include "admin_sidenav.html"%}
    <main class="main-wrap">
        {% include 'admin_nav.html' %}

        <section class="content-main">
            <div class="row mt-60">
                <div class="col-sm-12">
                    <div class="w-50 mx-auto text-center">
                        <img src="assets/imgs/theme/404.png" width="350" alt="Page Not Found">
                        <h3 class="mt-40 mb-15">Oops! Page not found</h3>
                        <p>It's looking like you may have taken a wrong turn. Don't worry... it happens to the best of us. Here's a little tip that might help you get back on track.</p>
                        <a href="index.html" class="btn btn-primary mt-4"><i class="material-icons md-keyboard_return"></i> Back to main</a>
                    </div>
                </div>
            </div>
        </section> <!-- content-main end// -->
        <footer class="main-footer font-xs">
            <div class="row pb-30 pt-15">
                <div class="col-sm-6">
                    <script>
                    document.write(new Date().getFullYear())
                    </script> ©, Evara - HTML Ecommerce Template .
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-end">
                        All rights reserved
                    </div>
                </div>
            </div>
        </footer>
    </main>
   {% endblock content %}